<?php


namespace calderawp\caldera\DataSource\WordPressData;

use calderawp\DB\Exceptions\InvalidColumnException;
use calderawp\DB\Table;

class PostTypeWithCustomMetaTable extends PostType
{

	/** @var Table */
	protected $table;


	/**
	 * @param string $column
	 * @param string $value
	 *
	 * @return array
	 * @throws InvalidColumnException
	 */
	public function findByMetaColumn(string $column, string $value): array
	{
		if (!$this->getMetaTable()->isAllowedKey($column)) {
			throw new InvalidColumnException();
		}
		return $this->getMetaTable()->findWhere($column, $value);
	}

	/**
	 * @param int $postId
	 *
	 * @return array
	 * @throws InvalidColumnException
	 */
	public function getMetaRow(int $postId): array
	{
		return $this->getMetaTable()->findWhere('post_id', $postId);
	}

	/**
	 * @param int $postId
	 * @param string $metaColumn
	 *
	 * @return mixed
	 * @throws InvalidColumnException
	 */
	public function getMetaValue(int $postId, string $metaColumn)
	{
		$row = $this->getMetaRow($postId);
		if (!empty($row) && isset($row[ $metaColumn ])) {
			return $row[ $metaColumn ];
		}

		throw new InvalidColumnException();
	}

	/**
	 * @return Table
	 */
	public function getMetaTable(): Table
	{
		return $this->table;
	}

	/**
	 * @param Table $table
	 *
	 * @return PostTypeWithCustomMetaTable
	 */
	public function setMetaTable(Table $table): PostTypeWithCustomMetaTable
	{
		$this->table = $table;
		return $this;
	}

	/** @inheritdoc */
	public function findIn(array $ins, string $column): array
	{

		if ($this->isMetaColumn($column)) {
			$metaResults = $this->getMetaTable()->findIn($ins, $column);
			return $this->collectPostsFromMetaResults($metaResults);
		}else{
			$posts = parent::findIn($ins,$column);

			if( ! empty($posts)){
				$postIds = array_column($posts, 'ID' );
				$metaResults = $this->getMetaTable()->findIn($postIds, 'post_id');
				return $this->collectPostsFromMetaResults($metaResults);

			}

		}

	}

	/** @inheritdoc */
	public function findWhere(string $column, $value): array
	{
		if ($this->isMetaColumn($column)) {
			$metaResults =  $this->getMetaTable()->findWhere($column, $value);
			return $this->collectPostsFromMetaResults($metaResults);
		}
		return parent::findWhere($column, $value);
	}

	/**
	 * @inheritDoc
	 */
	public function create(array $data): int
	{
		$prepared = $this->sortData($data);

		$saved = parent::create($prepared[ 'post' ]);
		if ($saved) {
			$prepared[ 'meta' ][ 'post_id' ] = $saved;
			$this->getMetaTable()->create($prepared[ 'meta' ]);
		}
		return $saved;
	}


	/**
	 * @inheritDoc
	 */
	public function update(int $id, array $data): array
	{
		$post = get_post($id,ARRAY_A);
		$prepared = $this->sortData($data);
		try {
			$metaRow = $this->getMetaTable()->findWhere('post_id', $post['ID']);
			$metaData = $this->getMetaTable()->update($metaRow[ 'id' ], $prepared[ 'meta' ]);
		} catch (\Exception $e) {
			$metaData = [];
		}

		$_data = $prepared['post'];
		unset($_data['meta']);
		$data =  parent::update($post['ID'], $_data);
		$data[ 'meta' ] = $metaData;
		return $data;
	}

	protected function sortData($data)
	{
		$prepared[ 'meta' ] = [];
		$prepared[ 'post' ] = [];
		foreach ($data as $key => $value) {
			if ($this->isMetaColumn($key)) {
				$prepared[ 'meta' ][ $key ] = $value;
			} else {
				$prepared[ 'post' ][ $key ] = $value;
			}
		}

		if( empty( $prepared[ 'post' ]['post_title'] ) ){
			$prepared[ 'post' ][ 'post_title' ] = md5(serialize($prepared));
		}
		$prepared[ 'post' ]['post_type'] = $this->getPostType();

		return $prepared;
	}

	public function read(int $id): array
	{
		$post = parent::read($id);
		$posts = $this->byPostId($post['ID']);
		return ! empty($posts) ? $posts[0] : [];

	}

	protected function byPostId(int $postId )
	{
		return $this->findWhere( 'post_id', $postId );
	}

	/**
	 * @inheritDoc
	 */
	public function anonymize(int $id, string $column): array
	{
		if ($this->isMetaColumn($column)) {
			$post = parent::read($id);
			return $this->getMetaTable()->anonymize($post['ID'], $column);
		}
		return parent::anonymize($id, $column);
	}

	/**
	 * @inheritDoc
	 */
	public function delete(int $id): bool
	{
		try {
			$metaRow = $this->getMetaTable()->read($id);
			$this->getMetaTable()->delete($metaRow[ 'id' ]);
		} catch (\Exception $e) {
		}
		return parent::delete($id); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	public function findById(int $id): array
	{
		$post = parent::read($id);
		$metaData = $this->getMetaTable()->findWhere('post_id', $id );
		if (is_array($metaData) && ! empty( $metaData )) {
			$post[ 'meta' ] = isset($metaData[ 0 ]) ? $metaData[ 0 ] : [];
		} else {
			$post[ 'meta' ] = [];
		}
		return $post;

	}


	protected function isMetaColumn(string $column): bool
	{
		return $this->getMetaTable()->isAllowedKey($column);
	}

	/**
	 * @param array $metaResults
	 *
	 * @return array
	 * @throws InvalidColumnException
	 */
	protected function collectPostsFromMetaResults(array $metaResults): array
	{
		$results = [];

		if (! empty( $metaResults )) {
			foreach ($metaResults as $result) {
				$postIds[] = $result[ 'post_id' ];
			}
			$postIds = [];
			$posts = parent::findIn($postIds, 'ID');
			foreach ($posts as $post) {
				foreach ($metaResults as $i => $result) {
					if ($post[ 'ID' ] == $result[ 'post_id' ]) {
						$results[] = array_merge((array)$post, ['meta' => $result]);
						unset($metaResults[ $i ]);
						break;
					}
				}
			}
		}
		return $results;
	}


}
